apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    release: {{ .Release.Name }}
    role: tensorboard
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tensorboard.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        role: tensorboard
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: tensorboard
          image: "{{ .Values.tensorboard.image.repository }}:{{ .Values.tensorboard.image.tag }}"
          imagePullPolicy: {{ .Values.tensorboard.image.pullPolicy }}
          command: ["tensorboard"]
          args:
          - --logdir={{ .Values.tensorboard.logdir }}
          - --port={{ .Values.service.internalPort }}
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.tensorboard.resources | indent 13 }}
          volumeMounts: 
          - name: data
            mountPath: {{ .Values.global.persistence.mountPath }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.global.persistence.name }}
