apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  completions: {{ .Values.worker.replicaCount }}
  parallelism: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
        role: worker
        release: {{ .Release.Name }}
        job: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["bootstrap"]
          args:
          - --ps_num={{ .Values.ps.replicaCount }}
          - --worker_num={{ .Values.worker.replicaCount }}
          - --job_name={{ .Release.Name }}
          - --role=worker
          - --cmd={{ .Values.global.cmd }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_DIR
              value: {{ .Values.global.persistence.logDir }}
          ports:
          - containerPort: 2222
          resources:
{{ toYaml .Values.worker.resources | indent 13 }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.global.persistence.mountPath }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.global.persistence.name }}
